### ISSUE TITLE
运行命令日志报错，错误日志信息如下

### ISSUE THREAD

**Issue by littleQing** [qibin0506/ChatRoom-PWA#1]
./server.go: line 1: package: command not found
./server.go: line 2: $'\r': command not found
./server.go: line 3: syntax error near unexpected token `$'\r''
./server.go: line 3: `import (
'

**Comment by qibin0506** [comment]
用编译好了的，或者自己编译，不能直接运行go文件。

**Comment by littleQing** [comment]
server.go 文件内容：
[root@iZ8u05vd83yntwZ chatroom]# cat server.cfg 
{
    "max_life_time_minute": 10,
    "listen_addr": "bighua.wang:8080/",
    "cert_file": "./keys/214805939580641.pem",
    "cert_key_file": "./keys/214805939580641.key",
    "token": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDboBS5V8jSj49WsRb6hP+65xPZi4S/PK32y0g2BG7A2EEO1Mwc21VLq9dyPjJJb5JYY6XPzeCtjzzrAp0yCSLfqJ2JdfJQLQZK/bkxtFHYTEnTm3syDm9FR9rCpDuCJiGF/ZgN6QKSIRDnVIotbd97r2SRcPTenaB1GyDyfh2xD0SsuxKNQEK1qIzFUZDUGjGP07x4CJBGjgH9aDX+4raDxdxJgwTTrSOxb+CQE20N+jTzcqY9VRNI369/shaitit4QXAoIPS8CbsU9X40VruCW5G4A9lvpT9SZWIsYHZmheQI0prd5l/93ccRM1mD82VT7ESPbK+5aOnFhhG0dTNV GitLab-SSHKey"
运行 go build server.go编译好server文件后
运行 nohup ./server & 
nohup: ignoring input and appending output to ‘nohup.out’

nohup.out无错误日志，但访问不了 https://bighua.wang:8080

**Comment by qibin0506** [comment]
检查一下域名是否正常解析
